### PR TITLE
Put search-form inside of the navigation bar.

### PR DESCRIPTION
**Pull request by novialriptide**
## Before
image

## After
image

### CODE REVIEW

**Review by fangerer — APPROVED** [review]
LGTM and I think it is common to have the search field in the navigation bar. We really appreciate contributions to the website! Thank you!

**Comment by hodgestar** [comment]
Woot! Is it possible to right align the search bar in the header?

**Comment by novialriptide** [comment]
> Woot! Is it possible to right align the search bar in the header?

Yup, I'll do it in a second.

**Comment by novialriptide** [comment]
I'm currently also busy with finals right now, but do you still want the search bar to be on the right side?

**Comment by hodgestar** [comment]
@novialriptide From my side, yes please!

**Pull request merged**
